"""GitHub Integration - Auto PR Creation"""

import os
from github import Github
from git import Repo
from pathlib import Path
from datetime import datetime
from loguru import logger

class GitHubPR:
    def __init__(self, repo_path: str = "."):
        self.repo_path = Path(repo_path).resolve()
        self.token = os.getenv("GITHUB_TOKEN")
        self.repo_name = os.getenv("GITHUB_REPO")
        
        if not self.token or not self.repo_name:
            logger.warning("GitHub not configured. Set GITHUB_TOKEN and GITHUB_REPO")
            self.gh = None
            return
        
        self.gh = Github(self.token)
        self.repo = self.gh.get_repo(self.repo_name)
        self.local_repo = Repo(self.repo_path)
    
    def create_branch(self, branch_name: str = None) -> str:
        """Create a new branch for fixes"""
        if not branch_name:
            branch_name = f"gutshape-fix-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        
        # Create branch from main
        main_branch = self.local_repo.active_branch
        new_branch = self.local_repo.create_head(branch_name, main_branch.commit)
        new_branch.checkout()
        
        logger.info(f"Created branch: {branch_name}")
        return branch_name
    
    def commit_changes(self, message: str = "GutShape: Auto-fix security issues"):
        """Commit all changes"""
        self.local_repo.index.add('*')
        self.local_repo.index.commit(message)
        logger.info("Committed changes")
    
    def push_branch(self, branch_name: str):
        """Push branch to remote"""
        origin = self.local_repo.remote(name='origin')
        origin.push(refspec=f'{branch_name}:{branch_name}')
        logger.info(f"Pushed branch: {branch_name}")
    
    def create_pr(self, branch_name: str, title: str = None, body: str = None) -> int:
        """Create Pull Request"""
        if not title:
            title = " GutShape: Auto-fix security vulnerabilities"
        
        if not body:
            body = """##  This PR was auto-generated by GutShape

### Changes Made:
- Replaced hardcoded secrets with environment variables
- Added proper security practices

### Please Review:
- [ ] Verify the changes work in your environment
- [ ] Set the required environment variables
- [ ] Run tests before merging

### Auto-Fix Details:
- Run `gutshape scan` to verify
- Run `gutshape apply` for more fixes
"""
        
        pr = self.repo.create_pull(
            title=title,
            body=body,
            head=branch_name,
            base="main"
        )
        
        logger.info(f"Created PR #{pr.number}: {pr.html_url}")
        return pr.number
    
    def auto_fix_and_pr(self, fixes: list) -> int:
        """Complete workflow: fix, commit, push, create PR"""
        if not self.gh:
            logger.error("GitHub not configured")
            return None
        
        branch = self.create_branch()
        self.commit_changes()
        self.push_branch(branch)
        pr_number = self.create_pr(branch)
        
        return pr_number
